### ISSUE TITLE
Mobile Meta Tag

### ISSUE THREAD

**Issue by kenmazaika** [jasyw5/projectone#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by jasyw5** [comment]
Hey Ken,

I added the meta tags and tested it out on my phone - it looks a lot better now! Thanks for the tip. let me know your thoughts.

**Comment by kenmazaika** [comment]
Looks perfect!  :+1:
